// Location work karvane wala

const locations = [
    "Port Blair, Andaman and Nicobar Islands",
    "Adoni, Andhra Pradesh",
    "Amaravati, Andhra Pradesh",
    "Anantapur, Andhra Pradesh",
    "Chandragiri, Andhra Pradesh",
    "Chittoor, Andhra Pradesh",
    "Dowlaiswaram, Andhra Pradesh",
    "Eluru, Andhra Pradesh",
    "Guntur, Andhra Pradesh",
    "Kadapa, Andhra Pradesh",
    "Kakinada, Andhra Pradesh",
    "Kurnool, Andhra Pradesh",
    "Machilipatnam, Andhra Pradesh",
    "Nagarjunakoṇḍa, Andhra Pradesh",
    "Rajahmundry, Andhra Pradesh",
    "Srikakulam, Andhra Pradesh",
    "Tirupati, Andhra Pradesh",
    "Vijayawada, Andhra Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Vizianagaram, Andhra Pradesh",
    "Yemmiganur, Andhra Pradesh",
    "Addanki, Andhra Pradesh",
    "Allagadda, Andhra Pradesh",
    "Amalapuram, Andhra Pradesh",
    "Amudalavalasa, Andhra Pradesh",
    "Atmakur, Andhra Pradesh",
    "Bapatla, Andhra Pradesh",
    "Bobbili, Andhra Pradesh",
    "Budwel, Andhra Pradesh",
    "Cheemakurthy, Andhra Pradesh",
    "Chirala, Andhra Pradesh",
    "Dhone, Andhra Pradesh",
    "Giddalur, Andhra Pradesh",
    "Gollaprolu, Andhra Pradesh",
    "Gooty, Andhra Pradesh",
    "Gudivada, Andhra Pradesh",
    "Gudur, Andhra Pradesh",
    "Guntakal, Andhra Pradesh",
    "Hindupur, Andhra Pradesh",
    "Ichapuram, Andhra Pradesh",
    "Jaggaiahpet, Andhra Pradesh",
    "Jammalamadugu, Andhra Pradesh",
    "Jangareddygudem, Andhra Pradesh",
    "Kavali, Andhra Pradesh",
    "Kadiri, Andhra Pradesh",
    "Kalyanadurgam, Andhra Pradesh",
    "Kandukur, Andhra Pradesh",
    "Kanigiri, Andhra Pradesh",
    "Kovvur, Andhra Pradesh",
    "Macherla, Andhra Pradesh",
    "Madakasira, Andhra Pradesh",
    "Madanapalle, Andhra Pradesh",
    "Mandapeta, Andhra Pradesh",
    "Mangalagiri, Andhra Pradesh",
    "Markapur, Andhra Pradesh",
    "Nandyal, Andhra Pradesh",
    "Narasapur, Andhra Pradesh",
    "Narasaraopet, Andhra Pradesh",
    "Nellore, Andhra Pradesh",
    "Ongole, Andhra Pradesh",
    "Proddatur, Andhra Pradesh",
    "Tadepalligudem, Andhra Pradesh",
    "Tadpatri, Andhra Pradesh",
    "Tenali, Andhra Pradesh",
    "Itanagar, Arunachal Pradesh",
    "Dhuburi, Assam",
    "Dibrugarh, Assam",
    "Dispur, Assam",
    "Guwahati, Assam",
    "Jorhat, Assam",
    "Nagaon, Assam",
    "Sivasagar, Assam",
    "Silchar, Assam",
    "Tezpur, Assam",
    "Tinsukia, Assam",
    "Ara, Bihar",
    "Barauni, Bihar",
    "Begusarai, Bihar",
    "Bettiah, Bihar",
    "Bhagalpur, Bihar",
    "Bihar Sharif, Bihar",
    "Bodh Gaya, Bihar",
    "Buxar, Bihar",
    "Chapra, Bihar",
    "Darbhanga, Bihar",
    "Dehri, Bihar",
    "Dinapur Nizamat, Bihar",
    "Gaya, Bihar",
    "Hajipur, Bihar",
    "Jamalpur, Bihar",
    "Katihar, Bihar",
    "Madhubani, Bihar",
    "Motihari, Bihar",
    "Munger, Bihar",
    "Muzaffarpur, Bihar",
    "Patna, Bihar",
    "Purnia, Bihar",
    "Pusa, Bihar",
    "Saharsa, Bihar",
    "Samastipur, Bihar",
    "Sasaram, Bihar",
    "Sitamarhi, Bihar",
    "Siwan, Bihar",
    "Chandigarh, Chandigarh",
    "Ambikapur, Chhattisgarh",
    "Bhilai, Chhattisgarh",
    "Bilaspur, Chhattisgarh",
    "Dhamtari, Chhattisgarh",
    "Durg, Chhattisgarh",
    "Jagdalpur, Chhattisgarh",
    "Raipur, Chhattisgarh",
    "Rajnandgaon, Chhattisgarh",
    "Daman, Dadra and Nagar Haveli and Daman and Diu",
    "Diu, Dadra and Nagar Haveli and Daman and Diu",
    "Silvassa, Dadra and Nagar Haveli and Daman and Diu",
    "Delhi, Delhi",
    "New Delhi, Delhi",
    "Madgaon, Goa",
    "Panaji, Goa",
    "Ahmadabad, Gujarat",
    "Amreli, Gujarat",
    "Bharuch, Gujarat",
    "Bhavnagar, Gujarat",
    "Bhuj, Gujarat",
    "Dwarka, Gujarat",
    "Gandhinagar, Gujarat",
    "Godhra, Gujarat",
    "Jamnagar, Gujarat",
    "Junagadh, Gujarat",
    "Kandla, Gujarat",
    "Khambhat, Gujarat",
    "Kheda, Gujarat",
    "Mahesana, Gujarat",
    "Morbi, Gujarat",
    "Nadiad, Gujarat",
    "Navsari, Gujarat",
    "Okha, Gujarat",
    "Palanpur, Gujarat",
    "Patan, Gujarat",
    "Porbandar, Gujarat",
    "Rajkot, Gujarat",
    "Surat, Gujarat",
    "Surendranagar, Gujarat",
    "Valsad, Gujarat",
    "Veraval, Gujarat",
    "Vadodara, Gujarat",
    "Anand, Gujarat",
    "Gandhidham, Gujarat",
    "Ambala, Haryana",
    "Bhiwani, Haryana",
    "Faridabad, Haryana",
    "Firozpur Jhirka, Haryana",
    "Gurugram, Haryana",
    "Hansi, Haryana",
    "Hisar, Haryana",
    "Jind, Haryana",
    "Kaithal, Haryana",
    "Karnal, Haryana",
    "Kurukshetra, Haryana",
    "Panipat, Haryana",
    "Pehowa, Haryana",
    "Rewari, Haryana",
    "Rohtak, Haryana",
    "Sirsa, Haryana",
    "Sonipat, Haryana",
    "Bilaspur, Himachal Pradesh",
    "Chamba, Himachal Pradesh",
    "Dalhousie, Himachal Pradesh",
    "Dharmshala, Himachal Pradesh",
    "Hamirpur, Himachal Pradesh",
    "Kangra, Himachal Pradesh",
    "Kullu, Himachal Pradesh",
    "Mandi, Himachal Pradesh",
    "Nahan, Himachal Pradesh",
    "Shimla, Himachal Pradesh",
    "Una, Himachal Pradesh",
    "Anantnag, Jammu and Kashmir",
    "Baramula, Jammu and Kashmir",
    "Doda, Jammu and Kashmir",
    "Gulmarg, Jammu and Kashmir",
    "Jammu, Jammu and Kashmir",
    "Kathua, Jammu and Kashmir",
    "Punch, Jammu and Kashmir",
    "Rajouri, Jammu and Kashmir",
    "Srinagar, Jammu and Kashmir",
    "Udhampur, Jammu and Kashmir",
    "Bokaro, Jharkhand",
    "Chaibasa, Jharkhand",
    "Deoghar, Jharkhand",
    "Dhanbad, Jharkhand",
    "Dumka, Jharkhand",
    "Giridih, Jharkhand",
    "Hazaribag, Jharkhand",
    "Jamshedpur, Jharkhand",
    "Jharia, Jharkhand",
    "Rajmahal, Jharkhand",
    "Ranchi, Jharkhand",
    "Saraikela, Jharkhand",
    "Badami, Karnataka",
    "Ballari, Karnataka",
    "Bengaluru, Karnataka",
    "Belagavi, Karnataka",
    "Bhadravati, Karnataka",
    "Bidar, Karnataka",
    "Chikkamagaluru, Karnataka",
    "Chitradurga, Karnataka",
    "Davangere, Karnataka",
    "Halebid, Karnataka",
    "Hassan, Karnataka",
    "Hubballi-Dharwad, Karnataka",
    "Kalaburagi, Karnataka",
    "Kolar, Karnataka",
    "Madikeri, Karnataka",
    "Mandya, Karnataka",
    "Mangaluru, Karnataka",
    "Mysuru, Karnataka",
    "Raichur, Karnataka",
    "Shivamogga, Karnataka",
    "Shravanabelagola, Karnataka",
    "Shrirangapattana, Karnataka",
    "Tumakuru, Karnataka",
    "Vijayapura, Karnataka",
    "Alappuzha, Kerala",
    "Vatakara, Kerala",
    "Idukki, Kerala",
    "Kannur, Kerala",
    "Kochi, Kerala",
    "Kollam, Kerala",
    "Kottayam, Kerala",
    "Kozhikode, Kerala",
    "Mattancheri, Kerala",
    "Palakkad, Kerala",
    "Thalassery, Kerala",
    "Thiruvananthapuram, Kerala",
    "Thrissur, Kerala",
    "Kargil, Ladakh",
    "Leh, Ladakh",
    "Balaghat, Madhya Pradesh",
    "Barwani, Madhya Pradesh",
    "Betul, Madhya Pradesh",
    "Bharhut, Madhya Pradesh",
    "Bhind, Madhya Pradesh",
    "Bhojpur, Madhya Pradesh",
    "Bhopal, Madhya Pradesh",
    "Burhanpur, Madhya Pradesh",
    "Chhatarpur, Madhya Pradesh",
    "Chhindwara, Madhya Pradesh",
    "Damoh, Madhya Pradesh",
    "Datia, Madhya Pradesh",
    "Dewas, Madhya Pradesh",
    "Dhar, Madhya Pradesh",
    "Dr. Ambedkar Nagar, Madhya Pradesh",
    "Guna, Madhya Pradesh",
    "Gwalior, Madhya Pradesh",
    "Hoshangabad, Madhya Pradesh",
    "Indore, Madhya Pradesh",
    "Itarsi, Madhya Pradesh",
    "Jabalpur, Madhya Pradesh",
    "Jhabua, Madhya Pradesh",
    "Khajuraho, Madhya Pradesh",
    "Khandwa, Madhya Pradesh",
    "Khargone, Madhya Pradesh",
    "Maheshwar, Madhya Pradesh",
    "Mandla, Madhya Pradesh",
    "Mandsaur, Madhya Pradesh",
    "Morena, Madhya Pradesh",
    "Murwara, Madhya Pradesh",
    "Narsimhapur, Madhya Pradesh",
    "Narsinghgarh, Madhya Pradesh",
    "Narwar, Madhya Pradesh",
    "Neemuch, Madhya Pradesh",
    "Nowgong, Madhya Pradesh",
    "Orchha, Madhya Pradesh",
    "Panna, Madhya Pradesh",
    "Raisen, Madhya Pradesh",
    "Rajgarh, Madhya Pradesh",
    "Ratlam, Madhya Pradesh",
    "Rewa, Madhya Pradesh",
    "Sagar, Madhya Pradesh",
    "Sarangpur, Madhya Pradesh",
    "Satna, Madhya Pradesh",
    "Sehore, Madhya Pradesh",
    "Seoni, Madhya Pradesh",
    "Shahdol, Madhya Pradesh",
    "Shajapur, Madhya Pradesh",
    "Sheopur, Madhya Pradesh",
    "Shivpuri, Madhya Pradesh",
    "Ujjain, Madhya Pradesh",
    "Vidisha, Madhya Pradesh",
    "Ahmadnagar, Maharashtra",
    "Akola, Maharashtra",
    "Amravati, Maharashtra",
    "Aurangabad, Maharashtra",
    "Bhandara, Maharashtra",
    "Bhusawal, Maharashtra",
    "Bid, Maharashtra",
    "Buldhana, Maharashtra",
    "Chandrapur, Maharashtra",
    "Daulatabad, Maharashtra",
    "Dhule, Maharashtra",
    "Jalgaon, Maharashtra",
    "Kalyan, Maharashtra",
    "Karli, Maharashtra",
    "Kolhapur, Maharashtra",
    "Mahabaleshwar, Maharashtra",
    "Malegaon, Maharashtra",
    "Matheran, Maharashtra",
    "Mumbai, Maharashtra",
    "Nagpur, Maharashtra",
    "Nanded, Maharashtra",
    "Nashik, Maharashtra",
    "Osmanabad, Maharashtra",
    "Pandharpur, Maharashtra",
    "Parbhani, Maharashtra",
    "Pune, Maharashtra",
    "Ratnagiri, Maharashtra",
    "Sangli, Maharashtra",
    "Satara, Maharashtra",
    "Sevagram, Maharashtra",
    "Solapur, Maharashtra",
    "Thane, Maharashtra",
    "Ulhasnagar, Maharashtra",
    "Vasai-Virar, Maharashtra",
    "Wardha, Maharashtra",
    "Yavatmal, Maharashtra",
    "Pimpri-Chinchwad, Maharashtra",
    "Navi Mumbai, Maharashtra",
    "Mira-Bhayandar, Maharashtra",
    "Bhiwandi-Nizampur, Maharashtra",
    "Panvel, Maharashtra",
    "Ichalkaranji, Maharashtra",
    "Latur, Maharashtra",
    "Jalna, Maharashtra",
    "Imphal, Manipur",
    "Cherrapunji, Meghalaya",
    "Shillong, Meghalaya",
    "Aizawl, Mizoram",
    "Lunglei, Mizoram",
    "Kohima, Nagaland",
    "Mon, Nagaland",
    "Phek, Nagaland",
    "Wokha, Nagaland",
    "Zunheboto, Nagaland",
    "Balangir, Odisha",
    "Baleshwar, Odisha",
    "Baripada, Odisha",
    "Bhubaneshwar, Odisha",
    "Brahmapur, Odisha",
    "Cuttack, Odisha",
    "Dhenkanal, Odisha",
    "Kendujhar, Odisha",
    "Konark, Odisha",
    "Koraput, Odisha",
    "Paradip, Odisha",
    "Phulabani, Odisha",
    "Puri, Odisha",
    "Sambalpur, Odisha",
    "Udayagiri, Odisha",
    "Rourkela, Odisha",
    "Karaikal, Puducherry",
    "Mahe, Puducherry",
    "Puducherry, Puducherry",
    "Yanam, Puducherry",
    "Amritsar, Punjab",
    "Batala, Punjab",
    "Faridkot, Punjab",
    "Firozpur, Punjab",
    "Gurdaspur, Punjab",
    "Hoshiarpur, Punjab",
    "Jalandhar, Punjab",
    "Kapurthala, Punjab",
    "Ludhiana, Punjab",
    "Nabha, Punjab",
    "Patiala, Punjab",
    "Rupnagar, Punjab",
    "Sangrur, Punjab",
    "Bathinda, Punjab",
    "Abu, Rajasthan",
    "Ajmer, Rajasthan",
    "Alwar, Rajasthan",
    "Amer, Rajasthan",
    "Barmer, Rajasthan",
    "Beawar, Rajasthan",
    "Bharatpur, Rajasthan",
    "Bhilwara, Rajasthan",
    "Bikaner, Rajasthan",
    "Bundi, Rajasthan",
    "Chittaurgarh, Rajasthan",
    "Churu, Rajasthan",
    "Dhaulpur, Rajasthan",
    "Dungarpur, Rajasthan",
    "Ganganagar, Rajasthan",
    "Hanumangarh, Rajasthan",
    "Jaipur, Rajasthan",
    "Jaisalmer, Rajasthan",
    "Jalor, Rajasthan",
    "Jhalawar, Rajasthan",
    "Jhunjhunu, Rajasthan",
    "Jodhpur, Rajasthan",
    "Kishangarh, Rajasthan",
    "Kota, Rajasthan",
    "Merta, Rajasthan",
    "Nagaur, Rajasthan",
    "Nathdwara, Rajasthan",
    "Pali, Rajasthan",
    "Phalodi, Rajasthan",
    "Pushkar, Rajasthan",
    "Sawai Madhopur, Rajasthan",
    "Shahpura, Rajasthan",
    "Sikar, Rajasthan",
    "Sirohi, Rajasthan",
    "Tonk, Rajasthan",
    "Udaipur, Rajasthan",
    "Gangtok, Sikkim",
    "Gyalshing, Sikkim",
    "Lachung, Sikkim",
    "Mangan, Sikkim",
    "Namchi, Sikkim",
    "Arcot, Tamil Nadu",
    "Chengalpattu, Tamil Nadu",
    "Chennai, Tamil Nadu",
    "Chidambaram, Tamil Nadu",
    "Coimbatore, Tamil Nadu",
    "Cuddalore, Tamil Nadu",
    "Dharmapuri, Tamil Nadu",
    "Dindigul, Tamil Nadu",
    "Erode, Tamil Nadu",
    "Kanchipuram, Tamil Nadu",
    "Kanniyakumari, Tamil Nadu",
    "Kodaikanal, Tamil Nadu",
    "Kumbakonam, Tamil Nadu",
    "Madurai, Tamil Nadu",
    "Mamallapuram, Tamil Nadu",
    "Nagappattinam, Tamil Nadu",
    "Nagercoil, Tamil Nadu",
    "Palayamkottai, Tamil Nadu",
    "Pudukkottai, Tamil Nadu",
    "Rajapalayam, Tamil Nadu",
    "Ramanathapuram, Tamil Nadu",
    "Salem, Tamil Nadu",
    "Thanjavur, Tamil Nadu",
    "Tiruchchirappalli, Tamil Nadu",
    "Tirunelveli, Tamil Nadu",
    "Tiruppur, Tamil Nadu",
    "Thoothukudi, Tamil Nadu",
    "Udhagamandalam, Tamil Nadu",
    "Vellore, Tamil Nadu",
    "Avadi, Tamil Nadu",
    "Ambattur, Tamil Nadu",
    "Hyderabad, Telangana",
    "Karimnagar, Telangana",
    "Khammam, Telangana",
    "Mahbubnagar, Telangana",
    "Nizamabad, Telangana",
    "Sangareddi, Telangana",
    "Warangal, Telangana",
    "Agartala, Tripura",
    "Agra, Uttar Pradesh",
    "Aligarh, Uttar Pradesh",
    "Amroha, Uttar Pradesh",
    "Ayodhya, Uttar Pradesh",
    "Azamgarh, Uttar Pradesh",
    "Bahraich, Uttar Pradesh",
    "Ballia, Uttar Pradesh",
    "Banda, Uttar Pradesh",
    "Bara Banki, Uttar Pradesh",
    "Bareilly, Uttar Pradesh",
    "Basti, Uttar Pradesh",
    "Bijnor, Uttar Pradesh",
    "Bithur, Uttar Pradesh",
    "Budaun, Uttar Pradesh",
    "Bulandshahr, Uttar Pradesh",
    "Deoria, Uttar Pradesh",
    "Etah, Uttar Pradesh",
    "Etawah, Uttar Pradesh",
    "Faizabad, Uttar Pradesh",
    "Farrukhabad-cum-Fatehgarh, Uttar Pradesh",
    "Fatehpur, Uttar Pradesh",
    "Fatehpur Sikri, Uttar Pradesh",
    "Ghaziabad, Uttar Pradesh",
    "Ghazipur, Uttar Pradesh",
    "Gonda, Uttar Pradesh",
    "Gorakhpur, Uttar Pradesh",
    "Hamirpur, Uttar Pradesh",
    "Hardoi, Uttar Pradesh",
    "Hathras, Uttar Pradesh",
    "Jalaun, Uttar Pradesh",
    "Jaunpur, Uttar Pradesh",
    "Jhansi, Uttar Pradesh",
    "Kannauj, Uttar Pradesh",
    "Kanpur, Uttar Pradesh",
    "Lakhimpur, Uttar Pradesh",
    "Lalitpur, Uttar Pradesh",
    "Lucknow, Uttar Pradesh",
    "Mainpuri, Uttar Pradesh",
    "Mathura, Uttar Pradesh",
    "Meerut, Uttar Pradesh",
    "Mirzapur-Vindhyachal, Uttar Pradesh",
    "Moradabad, Uttar Pradesh",
    "Muzaffarnagar, Uttar Pradesh",
    "Partapgarh, Uttar Pradesh",
    "Pilibhit, Uttar Pradesh",
    "Prayagraj, Uttar Pradesh",
    "Rae Bareli, Uttar Pradesh",
    "Rampur, Uttar Pradesh",
    "Saharanpur, Uttar Pradesh",
    "Sambhal, Uttar Pradesh",
    "Shahjahanpur, Uttar Pradesh",
    "Sitapur, Uttar Pradesh",
    "Sultanpur, Uttar Pradesh",
    "Tehri, Uttar Pradesh",
    "Varanasi, Uttar Pradesh",
    "Noida, Uttar Pradesh",
    "Almora, Uttarakhand",
    "Dehra Dun, Uttarakhand",
    "Haridwar, Uttarakhand",
    "Mussoorie, Uttarakhand",
    "Nainital, Uttarakhand",
    "Pithoragarh, Uttarakhand",
    "Alipore, West Bengal",
    "Alipur Duar, West Bengal",
    "Asansol, West Bengal",
    "Baharampur, West Bengal",
    "Bally, West Bengal",
    "Balurghat, West Bengal",
    "Bankura, West Bengal",
    "Baranagar, West Bengal",
    "Barasat, West Bengal",
    "Barrackpore, West Bengal",
    "Basirhat, West Bengal",
    "Bhatpara, West Bengal",
    "Bishnupur, West Bengal",
    "Budge Budge, West Bengal",
    "Burdwan, West Bengal",
    "Chandernagore, West Bengal",
    "Darjeeling, West Bengal",
    "Diamond Harbour, West Bengal",
    "Dum Dum, West Bengal",
    "Durgapur, West Bengal",
    "Halisahar, West Bengal",
    "Haora, West Bengal",
    "Hugli, West Bengal",
    "Ingraj Bazar, West Bengal",
    "Jalpaiguri, West Bengal",
    "Kalimpong, West Bengal",
    "Kamarhati, West Bengal",
    "Kanchrapara, West Bengal",
    "Kharagpur, West Bengal",
    "Cooch Behar, West Bengal",
    "Kolkata, West Bengal",
    "Krishnanagar, West Bengal",
    "Malda, West Bengal",
    "Midnapore, West Bengal",
    "Murshidabad, West Bengal",
    "Nabadwip, West Bengal",
    "Palashi, West Bengal",
    "Panihati, West Bengal",
    "Purulia, West Bengal",
    "Raiganj, West Bengal",
    "Santipur, West Bengal",
    "Shantiniketan, West Bengal",
    "Shrirampur, West Bengal",
    "Siliguri, West Bengal",
    "Siuri, West Bengal",
    "Tamluk, West Bengal",
    "Titagarh, West Bengal",
    "Haldia, West Bengal",
    "Bidhannagar, West Bengal",
    "New Town Kolkata, West Bengal",
    "Ahmedabad, Gujarat",
    "Vapi, Gujarat",
    "Ankleshwar, Gujarat",
    "Kalol, Gujarat",
    "Mehsana, Gujarat",
    "Dahod, Gujarat",
    "Botad, Gujarat",
    "Gir Somnath, Gujarat",
    "Devbhumi Dwarka, Gujarat",
    "Kachchh, Gujarat",
    "Banaskantha, Gujarat",
    "Sabarkantha, Gujarat",
    "Aravalli, Gujarat",
    "Narmada, Gujarat",
    "Tapi, Gujarat",
    "Dahanu, Gujarat",
    "Nasik, Maharashtra",
    "Ahmednagar, Maharashtra",
    "Sindhudurg, Maharashtra",
    "Raigad, Maharashtra",
    "Mumbai Suburban, Maharashtra",
    "Mumbai City, Maharashtra",
    "Palghar, Maharashtra",
    "Nandurbar, Maharashtra",
    "Hingoli, Maharashtra",
    "Beed, Maharashtra",
    "Washim, Maharashtra",
    "Gondia, Maharashtra",
    "Gadchiroli, Maharashtra",
    "Bangalore Urban, Karnataka",
    "Bangalore Rural, Karnataka",
    "Ramanagara, Karnataka",
    "Chikkaballapur, Karnataka",
    "Tumkur, Karnataka",
    "Davanagere, Karnataka",
    "Bagalkot, Karnataka",
    "Bijapur, Karnataka",
    "Gulbarga, Karnataka",
    "Koppal, Karnataka",
    "Gadag, Karnataka",
    "Dharwad, Karnataka",
    "Uttara Kannada, Karnataka",
    "Haveri, Karnataka",
    "Bellary, Karnataka",
    "Dakshina Kannada, Karnataka",
    "Udupi, Karnataka",
    "Kodagu, Karnataka",
    "Mysore, Karnataka",
    "Chamarajanagar, Karnataka",
    "Thiruvallur, Tamil Nadu",
    "Kancheepuram, Tamil Nadu",
    "Tiruvannamalai, Tamil Nadu",
    "Viluppuram, Tamil Nadu",
    "Namakkal, Tamil Nadu",
    "The Nilgiris, Tamil Nadu",
    "Krishnagiri, Tamil Nadu",
    "Nagapattinam, Tamil Nadu",
    "Thiruvarur, Tamil Nadu",
    "Sivaganga, Tamil Nadu",
    "Theni, Tamil Nadu",
    "Virudhunagar, Tamil Nadu",
    "Kanyakumari, Tamil Nadu",
    "Tirupur, Tamil Nadu",
    "Karur, Tamil Nadu",
    "Trichy, Tamil Nadu",
    "Perambalur, Tamil Nadu",
    "Ariyalur, Tamil Nadu",
    "East Godavari, Andhra Pradesh",
    "West Godavari, Andhra Pradesh",
    "Krishna, Andhra Pradesh",
    "Prakasam, Andhra Pradesh",
    "Sri Potti Sriramulu Nellore, Andhra Pradesh",
    "YSR Kadapa, Andhra Pradesh",
    "Adilabad, Telangana",
    "Komaram Bheem Asifabad, Telangana",
    "Mancherial, Telangana",
    "Nirmal, Telangana",
    "Jagtial, Telangana",
    "Peddapalli, Telangana",
    "Jayashankar Bhoopalpally, Telangana",
    "Mulugu, Telangana",
    "Bhadradri Kothagudem, Telangana",
    "Suryapet, Telangana",
    "Mahabubabad, Telangana",
    "Warangal Rural, Telangana",
    "Warangal Urban, Telangana",
    "Jangaon, Telangana",
    "Siddipet, Telangana",
    "Yadadri Bhuvanagiri, Telangana",
    "Rajanna Sircilla, Telangana",
    "Kamareddy, Telangana",
    "Medak, Telangana",
    "Sangareddy, Telangana",
    "Medchal Malkajgiri, Telangana",
    "Rangareddy, Telangana",
    "Vikarabad, Telangana",
    "Mahabubnagar, Telangana",
    "Jogulamba Gadwal, Telangana",
    "Wanaparthy, Telangana",
    "Nagarkurnool, Telangana",
    "Nalgonda, Telangana",
    "Kasaragod, Kerala",
    "Wayanad, Kerala",
    "Malappuram, Kerala",
    "Ernakulam, Kerala",
    "Pathanamthitta, Kerala",
    "Pathankot, Punjab",
    "Tarn Taran, Punjab",
    "Shahid Bhagat Singh Nagar, Punjab",
    "Fatehgarh Sahib, Punjab",
    "Moga, Punjab",
    "Muktsar, Punjab",
    "Mansa, Punjab",
    "Barnala, Punjab",
    "Mohali, Punjab",
    "Panchkula, Haryana",
    "Yamunanagar, Haryana",
    "Fatehabad, Haryana",
    "Charkhi Dadri, Haryana",
    "Mahendragarh, Haryana",
    "Gurgaon, Haryana",
    "Mewat, Haryana",
    "Palwal, Haryana",
    "Karauli, Rajasthan",
    "Dausa, Rajasthan",
    "Jalore, Rajasthan",
    "Rajsamand, Rajasthan",
    "Banswara, Rajasthan",
    "Chittorgarh, Rajasthan",
    "Baran, Rajasthan",
    "Pratapgarh, Rajasthan",
    "Tikamgarh, Madhya Pradesh",
    "Umaria, Madhya Pradesh",
    "Anuppur, Madhya Pradesh",
    "Sidhi, Madhya Pradesh",
    "Singrauli, Madhya Pradesh",
    "Alirajpur, Madhya Pradesh",
    "Harda, Madhya Pradesh",
    "Katni, Madhya Pradesh",
    "Narsinghpur, Madhya Pradesh",
    "Dindori, Madhya Pradesh",
    "Jyotiba Phule Nagar, Uttar Pradesh",
    "Baghpat, Uttar Pradesh",
    "Gautam Buddh Nagar, Uttar Pradesh",
    "Firozabad, Uttar Pradesh",
    "Kheri, Uttar Pradesh",
    "Unnao, Uttar Pradesh",
    "Farrukhabad, Uttar Pradesh",
    "Auraiya, Uttar Pradesh",
    "Kanpur Dehat, Uttar Pradesh",
    "Kanpur Nagar, Uttar Pradesh",
    "Mahoba, Uttar Pradesh",
    "Chitrakoot, Uttar Pradesh",
    "Pratapgarh, Uttar Pradesh",
    "Kaushambi, Uttar Pradesh",
    "Allahabad, Uttar Pradesh",
    "Ambedkar Nagar, Uttar Pradesh",
    "Shrawasti, Uttar Pradesh",
    "Balrampur, Uttar Pradesh",
    "Siddharthnagar, Uttar Pradesh",
    "Sant Kabir Nagar, Uttar Pradesh",
    "Maharajganj, Uttar Pradesh",
    "Kushinagar, Uttar Pradesh",
    "Mau, Uttar Pradesh",
    "Chandauli, Uttar Pradesh",
    "Sonbhadra, Uttar Pradesh",
    "Mirzapur, Uttar Pradesh",
    "Sant Ravidas Nagar, Uttar Pradesh",
    "Karimganj, Assam",
    "Hailakandi, Assam",
    "Golaghat, Assam",
    "Kokrajhar, Assam",
    "Dhubri, Assam",
    "Bongaigaon, Assam",
    "Goalpara, Assam",
    "Barpeta, Assam",
    "Morigaon, Assam",
    "Sonitpur, Assam",
    "Lakhimpur, Assam",
    "Dhemaji, Assam",
    "Karbi Anglong, Assam",
    "Dima Hasao, Assam",
    "Araria, Bihar",
    "Arwal, Bihar",
    "Aurangabad, Bihar",
    "Banka, Bihar",
    "Bhojpur, Bihar",
    "East Champaran, Bihar",
    "Gopalganj, Bihar",
    "Jamui, Bihar",
    "Jehanabad, Bihar",
    "Kaimur, Bihar",
    "Khagaria, Bihar",
    "Kishanganj, Bihar",
    "Lakhisarai, Bihar",
    "Madhepura, Bihar",
    "Nalanda, Bihar",
    "Nawada, Bihar",
    "Rohtas, Bihar",
    "Saran, Bihar",
    "Sheikhpura, Bihar",
    "Sheohar, Bihar",
    "Supaul, Bihar",
    "Vaishali, Bihar",
    "West Champaran, Bihar",
    "Balod, Chhattisgarh",
    "Baloda Bazar, Chhattisgarh",
    "Balrampur, Chhattisgarh",
    "Bastar, Chhattisgarh",
    "Bemetara, Chhattisgarh",
    "Bijapur, Chhattisgarh",
    "Dantewada, Chhattisgarh",
    "Gariaband, Chhattisgarh",
    "Janjgir Champa, Chhattisgarh",
    "Jashpur, Chhattisgarh",
    "Kabirdham, Chhattisgarh",
    "Kanker, Chhattisgarh",
    "Kondagaon, Chhattisgarh",
    "Korba, Chhattisgarh",
    "Koriya, Chhattisgarh",
    "Mahasamund, Chhattisgarh",
    "Mungeli, Chhattisgarh",
    "Narayanpur, Chhattisgarh",
    "Raigarh, Chhattisgarh",
    "Sukma, Chhattisgarh",
    "Surajpur, Chhattisgarh",
    "Surguja, Chhattisgarh",
    "Chatra, Jharkhand",
    "East Singhbhum, Jharkhand",
    "Garhwa, Jharkhand",
    "Godda, Jharkhand",
    "Gumla, Jharkhand",
    "Jamtara, Jharkhand",
    "Khunti, Jharkhand",
    "Koderma, Jharkhand",
    "Latehar, Jharkhand",
    "Lohardaga, Jharkhand",
    "Pakur, Jharkhand",
    "Palamu, Jharkhand",
    "Ramgarh, Jharkhand",
    "Sahibganj, Jharkhand",
    "Seraikela Kharsawan, Jharkhand",
    "Simdega, Jharkhand",
    "West Singhbhum, Jharkhand",
    "Angul, Odisha",
    "Boudh, Odisha",
    "Bhadrak, Odisha",
    "Bargarh, Odisha",
    "Balasore, Odisha",
    "Debagarh, Odisha",
    "Ganjam, Odisha",
    "Gajapati, Odisha",
    "Jharsuguda, Odisha",
    "Jajpur, Odisha",
    "Jagatsinghpur, Odisha",
    "Khordha, Odisha",
    "Keonjhar, Odisha",
    "Kalahandi, Odisha",
    "Kandhamal, Odisha",
    "Kendrapara, Odisha",
    "Malkangiri, Odisha",
    "Mayurbhanj, Odisha",
    "Nabarangpur, Odisha",
    "Nuapada, Odisha",
    "Nayagarh, Odisha",
    "Rayagada, Odisha",
    "Sonepur, Odisha",
    "Sundargarh, Odisha",
    "Alipurduar, West Bengal",
    "Birbhum, West Bengal",
    "Dakshin Dinajpur, West Bengal",
    "Hooghly, West Bengal",
    "Howrah, West Bengal",
    "Jhargram, West Bengal",
    "Nadia, West Bengal",
    "North 24 Parganas, West Bengal",
    "Paschim Bardhaman, West Bengal",
    "Paschim Medinipur, West Bengal",
    "Purba Bardhaman, West Bengal",
    "Purba Medinipur, West Bengal",
    "South 24 Parganas, West Bengal",
    "Uttar Dinajpur, West Bengal",
    "Kalyan-Dombivali, Maharashtra",
    "Vasai-Virar City, Maharashtra",
    "New Mumbai, Maharashtra",
    "Berhampur, Odisha",
    "Bhubaneswar, Odisha",
    "Tiruchirapalli, Tamil Nadu",
    "Greater Hyderabad, Telangana",
    "Greater Warangal, Telangana",
    "Dehradun, Uttarakhand",
    "Kavaratti, Lakshadweep",
    "Vishakhapatnam, Andhra Pradesh",
    "Kalburgi, Karnataka",
    "Bhachau, Gujarat",
    "Mandvi, Gujarat",
    "Mundra, Gujarat",
    "Adipur, Gujarat",
    "Anjar, Gujarat",
    "Rapar, Gujarat",
    "Chikhli, Gujarat",
    "Jalalpore, Gujarat",
    "Gandevi, Gujarat",
    "Bulsar, Gujarat",
    "Pardi, Gujarat",
    "Umbergaon, Gujarat",
    "Dharampur, Gujarat",
    "Bilimora, Gujarat",
    "Kamrej, Gujarat",
    "Bardoli, Gujarat",
    "Mahuva, Gujarat",
    "Vyara, Gujarat",
    "Songadh, Gujarat",
    "Ukai, Gujarat",
    "Hazira, Gujarat",
    "Sachin, Gujarat",
    "Mangrol, Gujarat",
    "Chorwad, Gujarat",
    "Kodinar, Gujarat",
    "Una, Gujarat",
    "Talala, Gujarat",
    "Keshod, Gujarat",
    "Maliya, Gujarat",
    "Kutiyana, Gujarat",
    "Ranavav, Gujarat",
    "Lalpur, Gujarat",
    "Kalawad, Gujarat",
    "Jodiya, Gujarat",
    "Dhrol, Gujarat",
    "Kalavad, Gujarat",
    "Bhanvad, Gujarat",
    "Jamkhambhaliya, Gujarat",
    "Khambhalia, Gujarat",
    "Salaya, Gujarat",
    "Sikka, Gujarat",
    "Rajpura, Punjab",
    "Sirhind, Punjab",
    "Khanna, Punjab",
    "Doraha, Punjab",
    "Payal, Punjab",
    "Samrala, Punjab",
    "Sahnewal, Punjab",
    "Raikot, Punjab",
    "Jagraon, Punjab",
    "Dehlon, Punjab",
    "Malerkotla, Punjab",
    "Ahmedgarh, Punjab",
    "Moonak, Punjab",
    "Sunam, Punjab",
    "Dhuri, Punjab",
    "Dera Bassi, Punjab",
    "Zirakpur, Punjab",
    "Lalru, Punjab",
    "Banur, Punjab",
    "Balachaur, Punjab",
    "Nangal, Punjab",
    "Una, Punjab",
    "Anandpur Sahib, Punjab",
    "Chamkaur Sahib, Punjab",
    "Kharar, Punjab",
    "Kurali, Punjab",
    "Morinda, Punjab",
    "Samana, Punjab",
    "Patran, Punjab",
    "Ghagga, Punjab",
    "Bassi Pathana, Punjab",
    "Amloh, Punjab",
    "Khanauri, Punjab",
    "Lehragaga, Punjab",
    "Dirba, Punjab",
    "Kokri, Punjab",
    "Budhlada, Punjab",
    "Sardulgarh, Punjab",
    "Rampura Phul, Punjab",
    "Maur, Punjab",
    "Kotkapura, Punjab",
    "Jaitu, Punjab",
    "Giddarbaha, Punjab",
    "Malout, Punjab",
    "Abohar, Punjab",
    "Fazilka, Punjab",
    "Jalalabad, Punjab",
    "Ferozeshah, Punjab",
    "Guru Har Sahai, Punjab",
    "Zira, Punjab",
    "Kalka, Haryana",
    "Pinjore, Haryana",
    "Naraingarh, Haryana",
    "Ambala Cantt, Haryana",
    "Barara, Haryana",
    "Shahabad, Haryana",
    "Thanesar, Haryana",
    "Cheeka, Haryana",
    "Pundri, Haryana",
    "Nilokheri, Haryana",
    "Indri, Haryana",
    "Gharaunda, Haryana",
    "Assandh, Haryana",
    "Safidon, Haryana",
    "Narwana, Haryana",
    "Uchana, Haryana",
    "Julana, Haryana",
    "Ganaur, Haryana",
    "Samalkha, Haryana",
    "Murthal, Haryana",
    "Gohana, Haryana",
    "Gannaur, Haryana",
    "Kharkhoda, Haryana",
    "Madlauda, Haryana",
    "Beri, Haryana",
    "Ateli, Haryana",
    "Kanina, Haryana",
    "Nangal Chaudhry, Haryana",
    "Narnaul, Haryana",
    "Mohindergarh, Haryana",
    "Dadri, Haryana",
    "Tosham, Haryana",
    "Loharu, Haryana",
    "Siwani, Haryana",
    "Barwala, Haryana",
    "Uklana, Haryana",
    "Narnaund, Haryana",
    "Ratia, Haryana",
    "Tohana, Haryana",
    "Jakhal, Haryana",
    "Dabwali, Haryana",
    "Kalanwali, Haryana",
    "Rania, Haryana",
    "Ellenabad, Haryana",
    "Nohar, Rajasthan",
    "Bhadra, Rajasthan",
    "Sangaria, Rajasthan",
    "Rawatsar, Rajasthan",
    "Suratgarh, Rajasthan",
    "Padampur, Rajasthan",
    "Anupgarh, Rajasthan",
    "Gharsana, Rajasthan",
    "Raisinghnagar, Rajasthan",
    "Pugal, Rajasthan",
    "Kolayat, Rajasthan",
    "Nokha, Rajasthan",
    "Khajuwala, Rajasthan",
    "Poogal, Rajasthan",
    "Dungargarh, Rajasthan",
    "Lunkaransar, Rajasthan",
    "Sujangarh, Rajasthan",
    "Taranagar, Rajasthan",
    "Sardarshahar, Rajasthan",
    "Ratangarh, Rajasthan",
    "Rajgarh, Rajasthan",
    "Pilani, Rajasthan",
    "Nawalgarh, Rajasthan",
    "Udaipurwati, Rajasthan",
    "Mandawa, Rajasthan",
    "Mukundgarh, Rajasthan",
    "Chirawa, Rajasthan",
    "Surajgarh, Rajasthan",
    "Lachhmangarh, Rajasthan",
    "Fatehpur, Rajasthan",
    "Ramgarh, Rajasthan",
    "Mahansar, Rajasthan",
    "Malsisar, Rajasthan",
    "Bissau, Rajasthan",
    "Khetri, Rajasthan",
    "Sindhanur, Karnataka",
    "Manvi, Karnataka",
    "Deodurg, Karnataka",
    "Lingsugur, Karnataka",
    "Kushtagi, Karnataka",
    "Gangavathi, Karnataka",
    "Karatagi, Karnataka",
    "Yelburga, Karnataka",
    "Hospet, Karnataka",
    "Hagaribommanahalli, Karnataka",
    "Hoovina Hadagali, Karnataka",
    "Harappanahalli, Karnataka",
    "Sandur, Karnataka",
    "Kudligi, Karnataka",
    "Siruguppa, Karnataka",
    "Indi, Karnataka",
    "Sindagi, Karnataka",
    "Basavana Bagevadi, Karnataka",
    "Muddebihal, Karnataka",
    "Mudhol, Karnataka",
    "Bilagi, Karnataka",
    "Hungund, Karnataka",
    "Jamkhandi, Karnataka",
    "Aihole, Karnataka",
    "Terdal, Karnataka",
    "Guledgudda, Karnataka",
    "Rabkavi Banhatti, Karnataka",
    "Saundatti, Karnataka",
    "Parasgad, Karnataka",
    "Ramdurg, Karnataka",
    "Savadatti, Karnataka",
    "Bailhongal, Karnataka",
    "Mudalgi, Karnataka",
    "Gokak, Karnataka",
    "Hukkeri, Karnataka",
    "Athani, Karnataka",
    "Chikkodi, Karnataka",
    "Nippani, Karnataka",
    "Khanapur, Karnataka",
    "Soundatti, Karnataka",
    "Hosur, Tamil Nadu",
    "Harur, Tamil Nadu",
    "Palacode, Tamil Nadu",
    "Pennagaram, Tamil Nadu",
    "Pochampalli, Tamil Nadu",
    "Denkanikottai, Tamil Nadu",
    "Shoolagiri, Tamil Nadu",
    "Uthangarai, Tamil Nadu",
    "Bargur, Tamil Nadu",
    "Anchetty, Tamil Nadu",
    "Rayakottai, Tamil Nadu",
    "Kelamangalam, Tamil Nadu",
    "Berigai, Tamil Nadu",
    "Vaniyambadi, Tamil Nadu",
    "Ambur, Tamil Nadu",
    "Tirupattur, Tamil Nadu",
    "Natrampalli, Tamil Nadu",
    "Alangayam, Tamil Nadu",
    "Gudiyattam, Tamil Nadu",
    "Pernambut, Tamil Nadu",
    "Jolarpettai, Tamil Nadu",
    "Bagayam, Tamil Nadu",
    "Yelagiri, Tamil Nadu",
    "Mel Malaiyanur, Tamil Nadu",
    "K V Kuppam, Tamil Nadu",
    "Sullurupeta, Andhra Pradesh",
    "Venkatagiri, Andhra Pradesh",
    "Udayagiri, Andhra Pradesh",
    "Kovur, Andhra Pradesh",
    "Indukurpet, Andhra Pradesh",
    "Tangutur, Andhra Pradesh",
    "Buchireddypalem, Andhra Pradesh",
    "Vidavalur, Andhra Pradesh",
    "Dorala, Andhra Pradesh",
    "Kaluvoya, Andhra Pradesh",
    "Vakadu, Andhra Pradesh",
    "Pellakur, Andhra Pradesh",
    "Manubolu, Andhra Pradesh",
    "Rapur, Andhra Pradesh",
    "Bogole, Andhra Pradesh",
    "Sangam, Andhra Pradesh",
    "Kondapuram, Andhra Pradesh",
    "Kota, Andhra Pradesh",
    "Muthukur, Andhra Pradesh",
    "Dakkili, Andhra Pradesh",
    "Ojili, Andhra Pradesh",
    "Ananthasagaram, Andhra Pradesh",
    "Chejerla, Andhra Pradesh",
    "Dagadarthi, Andhra Pradesh",
    "Kodavalur, Andhra Pradesh",
    "Podalakur, Andhra Pradesh",
    "Thotapalligudur, Andhra Pradesh",
    "Sydapuram, Andhra Pradesh",
    "Balayapalli, Andhra Pradesh",
    "Naidupet, Andhra Pradesh",
    "Changanassery, Kerala",
    "Vaikom, Kerala",
    "Ettumanoor, Kerala",
    "Erattupetta, Kerala",
    "Pala, Kerala",
    "Teekoy, Kerala",
    "Kaduthuruthy, Kerala",
    "Kumarakom, Kerala",
    "Manarcaud, Kerala",
    "Vechoor, Kerala",
    "Uzhavoor, Kerala",
    "Panachikkad, Kerala",
    "Ayarkunnam, Kerala",
    "Bharananganam, Kerala",
    "Chempu, Kerala",
    "Chirakkadavu, Kerala",
    "Elikulam, Kerala",
    "Kanakkary, Kerala",
    "Karoor, Kerala",
    "Kidangoor, Kerala",
    "Koruthodu, Kerala",
    "Kuravilangad, Kerala",
    "Lalam, Kerala",
    "Madappally, Kerala",
    "Manimala, Kerala",
    "Manjoor, Kerala",
    "Meenadom, Kerala",
    "Meenachil, Kerala",
    "Melukavu, Kerala",
    "Moonnilav, Kerala",
    "Mulakkulam, Kerala",
    "Mundakayam, Kerala",
    "Muvattupuzha, Kerala",
    "Neendoor, Kerala",
    "Njeezhoor, Kerala",
    "Pampady, Kerala",
    "Pariyaram, Kerala",
    "Payippadu, Kerala",
    "Poonjar, Kerala",
    "Ramapuram, Kerala",
    "Thalayazham, Kerala",
    "Thalayolaparambu, Kerala",
    "Thidanad, Kerala",
    "Thiruvarppu, Kerala",
    "Tv Puram, Kerala",
    "Udayanapuram, Kerala",
    "Vakathanam, Kerala",
    "Vazhappally, Kerala",
    "Vazhoor, Kerala",
    "Veliyannoor, Kerala",
    "Vellavoor, Kerala",
    "Velloor, Kerala",
    "Vijayapuram, Kerala",
    "Mayiladuthurai, Tamil Nadu",
    "Vedaranyam, Tamil Nadu",
    "Thiruthuraipoondi, Tamil Nadu",
    "Mannargudi, Tamil Nadu",
    "Nannilam, Tamil Nadu",
    "Needamangalam, Tamil Nadu",
    "Valangaiman, Tamil Nadu",
    "Kodavasal, Tamil Nadu",
    "Madukkur, Tamil Nadu",
    "Aranthangi, Tamil Nadu",
    "Gandarvakottai, Tamil Nadu",
    "Thirumayam, Tamil Nadu",
    "Alangudi, Tamil Nadu",
    "Karambakudi, Tamil Nadu",
    "Kulathur, Tamil Nadu",
    "Manamelkudi, Tamil Nadu",
    "Ponnamaravathi, Tamil Nadu",
    "Viralimalai, Tamil Nadu",
    "Kalayarkoil, Tamil Nadu",
    "Devakottai, Tamil Nadu",
    "Manamadurai, Tamil Nadu",
    "Singampunari, Tamil Nadu",
    "Ilayankudi, Tamil Nadu",
    "Karaikudi, Tamil Nadu",
    "Pillaiyanmanai, Tamil Nadu",
    "Tirupathur, Tamil Nadu",
    "Madhurai, Tamil Nadu",
    "Usilampatti, Tamil Nadu",
    "Andipatti, Tamil Nadu",
    "Periyakulam, Tamil Nadu",
    "Bodinayakanur, Tamil Nadu",
    "Uthamapalayam, Tamil Nadu",
    "Chinnamanur, Tamil Nadu",
    "Vedasandur, Tamil Nadu",
    "Kamuthi, Tamil Nadu",
    "Mudukulathur, Tamil Nadu",
    "Paramakudi, Tamil Nadu",
    "Rameswaram, Tamil Nadu",
    "Kilakarai, Tamil Nadu",
    "Sayalgudi, Tamil Nadu",
    "Tiruvadanai, Tamil Nadu",
    "Sivakasi, Tamil Nadu",
    "Tiruchuli, Tamil Nadu",
    "Sattur, Tamil Nadu",
    "Srivilliputhur, Tamil Nadu",
    "Sankarankovil, Tamil Nadu",
    "Vembakottai, Tamil Nadu",
    "Watrap, Tamil Nadu",
    "Aruppukkottai, Tamil Nadu",
    "Kariapatti, Tamil Nadu",
    "Tenkasi, Tamil Nadu",
    "Kadayanallur, Tamil Nadu",
    "Radhapuram, Tamil Nadu",
    "Nanguneri, Tamil Nadu",
    "Ambasamudram, Tamil Nadu",
    "Kallidaikurichi, Tamil Nadu",
    "Abbotabad, Tamil Nadu",
    "Cheranmadevi, Tamil Nadu",
    "Manur, Tamil Nadu",
    "Thisayanvilai, Tamil Nadu",
    "Kovilpatti, Tamil Nadu",
    "Ettayapuram, Tamil Nadu",
    "Kayathar, Tamil Nadu",
    "Vilathikulam, Tamil Nadu",
    "Sathankulam, Tamil Nadu",
    "Tiruchendur, Tamil Nadu",
    "Udangudi, Tamil Nadu",
    "Srivaikuntam, Tamil Nadu",
    "Alwarkurichi, Tamil Nadu",
    "Padmanabhapuram, Tamil Nadu",
    "Thuckalay, Tamil Nadu",
    "Thiruvattar, Tamil Nadu",
    "Kuzhithurai, Tamil Nadu",
    "Marthandam, Tamil Nadu",
    "Kalkulam, Tamil Nadu",
    "Vilavancode, Tamil Nadu",
    "Killiyoor, Tamil Nadu",
    "Kurunthancode, Tamil Nadu",
    "Munchirai, Tamil Nadu",
    "Thovalai, Tamil Nadu",
    "Agasteeswaram, Tamil Nadu",
    "Suchindram, Tamil Nadu",
    "Colachel, Tamil Nadu",
    "Rajakkamangalam, Tamil Nadu",
    "Eraniel, Tamil Nadu",
    "Muttom, Tamil Nadu"
];

  const locationInput = document.getElementById("location-input");
const results = document.getElementById("location-results");
const selected = document.getElementById("selected-locations");
const clearBtn = document.getElementById("clear-locations");
let selectedLocations = [];

locationInput.addEventListener("input", () => {
  const query = locationInput.value.toLowerCase();
  results.innerHTML = "";

  if (query.length === 0) {
    results.classList.add("hidden");
    return;
  }

  const filtered = locations.filter(
    (loc) =>
      loc.toLowerCase().includes(query) && !selectedLocations.includes(loc)
  );

  if (filtered.length > 0) {
    filtered.forEach((loc) => {
      const li = document.createElement("li");
      li.textContent = loc;
      li.className =
        "px-4 py-2 hover:bg-base-300 cursor-pointer text-left";
      li.onclick = () => selectLocation(loc);
      results.appendChild(li);
    });
    results.classList.remove("hidden");
  } else {
    results.classList.add("hidden");
  }
});

function selectLocation(loc) {
  if (!selectedLocations.includes(loc)) {
    selectedLocations.push(loc);

    const tag = document.createElement("div");
    tag.className = "location-chip";
    tag.innerHTML = `
      <span>${loc}</span>
      <button>&times;</button>
    `;

    tag.querySelector("button").onclick = () => {
      tag.style.opacity = "0"; 
      setTimeout(() => {
        selectedLocations = selectedLocations.filter((l) => l !== loc);
        tag.remove();
      }, 300);
    };

    selected.appendChild(tag);
  }

  locationInput.value = "";
  results.classList.add("hidden");
}

clearBtn.addEventListener("click", () => {
  const chips = document.querySelectorAll(".location-chip");
  chips.forEach((chip) => {
    chip.style.opacity = "0";
  });
  setTimeout(() => {
    selectedLocations = [];
    selected.innerHTML = "";
  }, 300);
});

document.addEventListener("click", (e) => {
  if (
    !e.target.closest("#location-input") &&
    !e.target.closest("#location-results")
  ) {
    results.classList.add("hidden");
  }
});